const char board_welcome[] =
"  a b c d e f g h i j k l m n o p q r s\n"
"A . . . . . . . . . . . . . . . . . . . \n"
"B . . . . . . . . . . . . . . . . . . . \n"
"C . . p p p . . . c c c . . p . . . p . \n"
"D . p . . . p . c . . . c . p p . p p . \n"
"E . p . . . . . c . . . c . p . p . p . \n"
"F . p . p p p . c . . . c . p . . . p . \n"
"G . p . . . p . c . . . c . p . . . p . \n"
"H . p . . . p . c . . . c . p . . . p . \n"
"I . . p p p . . . c c c . . p . . . p . \n"
"J . . . . . . . . . . . . . . . . . . . \n"
"K . . c c c . . p . . . p . c . . . c . \n"
"L . c . . . c . p . . p . . c . . . c . \n"
"M . c . . . c . p . p . . . c . . . c . \n"
"N . c . . . c . p p . . . . c . . . c . \n"
"O . c . . . c . p . p . . . c . . . c . \n"
"P . c . . . c . p . . p . . c . . . c . \n"
"Q . . c c c . . p . . . p . . c c c . . \n"
"R . . . . . . . . . . . . . . . . . . . \n"
"S . . . . . . . . . . . . . . . . . . . ";
